name: Build CJE Playbook

on:
  push:
    tags:
      - 'v*'           # Trigger on version tags (e.g., v0.2.1, v1.0.0)
    branches:
      - main           # Also build latest on main
  pull_request:
    paths:
      - 'docs/playbook/**'
      - 'cje/__version__.py'
      - '.github/workflows/build_playbook.yml'

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-bibtex-extra \
            biber

      - name: Test version extraction
        run: |
          cd docs/playbook
          make test-version

      - name: Build PDF
        run: |
          cd docs/playbook
          make pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cje-playbook-pdf
          path: docs/playbook/build/*.pdf
          retention-days: 90

      - name: Attach to Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: docs/playbook/build/*.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

  build-html:
    runs-on: ubuntu-latest
    needs: build-pdf  # Can run in parallel, but let's ensure PDF works first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build HTML
        run: |
          cd docs/playbook
          make html || echo "HTML build failed (pandoc may need additional setup)"

      - name: Upload HTML artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: cje-playbook-html
          path: docs/playbook/build/*.html
          retention-days: 90

      - name: Attach to Release (on tag)
        if: startsWith(github.ref, 'refs/tags/') && success()
        uses: softprops/action-gh-release@v1
        with:
          files: docs/playbook/build/*.html
          token: ${{ secrets.GITHUB_TOKEN}}
          draft: false
          prerelease: false
