name: Publish to TestPyPI

on:
  push:
    tags:
      - 'test-v*'  # Trigger on tags like test-v0.2.0
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  id-token: write  # Required for OIDC

jobs:
  publish-test:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment: testpypi  # Optional: use GitHub environment for approval gate

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Build package
        run: poetry build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          print-hash: true
